### ISSUE TITLE
Fix respec errors and retain wedIDLv1 hyperlinks

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#83]
See https://github.com/w3c/media-source/issues/68#issuecomment-221861108

Assigning to you, @plehegar

**Comment by wolenetz** [comment]
Hmm. This was closed accidentally yesterday, apparently.

**Comment by mwatson2** [comment]
There are no ReSpec errors reported on the page at present, but there are errors reported on the JS console:

```
respec-w3c-common.js:8 ERROR:  TypeError: tmp.indexOf is not a function(…)(anonymous function) @ respec-w3c-common.js:8
respec-w3c-common.js:8 ERROR:  TypeError: e.definitionMap[t].forEach is not a function(…)
```
and

```
respec-w3c-common.js:8 Uncaught (in promise) TypeError: t[e].map is not a function(…)
```

Does anyone know what these are and whether they are a problem ?

**Comment by wolenetz** [comment]
I fixed a few of these in the byte stream format specs (in pending PR(s)) by cleaning up the local stream-respec.html's definitionMap for entries that had more recently had explicit definitions added in media-source.js. Example: https://github.com/w3c/media-source/pull/122/files#diff-a311f960a81a23caf155c43c6c53f3e5R101

**Comment by mwatson2** [comment]
PR #127 

Removing the empty definitionMap fixes the third of those JS errors and allows the ReSpec execution to complete (there were problems with links out of the IDL before).

The first two error remain - they were present before this PR as well.

**Comment by wolenetz** [comment]
> The first two error remain - they were present before this PR as well.

I'll file a separate issue to track fixing those two.

**Comment by mwatson2** [comment]
Regarding `appendBuffer` overloading, WebIDL defined `BufferSource` as `ArrayBuffer or ArrayBufferView`, so I suggest we switch to using that (this would be a editorial change and would fix the linking problems).

**Comment by wolenetz** [comment]
I'll review the current PR soon. If it doesn't yet contain "ArrayBuffer or ArrayBufferView", I agree that sounds most expedient and correct (to prevent manual fixups of the regenerated spec in future, I hope, too).

**Comment by wolenetz** [comment]
I see the "BufferSource" usage in the PR accomplishes the elimination of explicit appendBuffer overloading. Good stuff :)
